# Netlify config for KARE Hall Booking frontend

[build]
  command = "npm run build"
  publish = "dist"

# Proxy API requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://karehallbooking-g695.onrender.com/api/:splat"
  status = 200
  force = true

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


